### ISSUE TITLE
Could you please provide the requirements.txt file to run the experiment?

### ISSUE THREAD

**Issue by Asifbinsyed** [gianlucatruda/TableDiffusion#2]

**Comment by gianlucatruda** [comment]
Hi @Asifbinsyed. The dependencies of this project are managed in `pyproject.toml`. I highly recommend using [poetry](https://python-poetry.org/docs/) to manage the environment and dependencies for this project, as the version compatibility is very specific and fiddly for some of the required libraries.

After you've installed poetry, you can use these commands inside the project:
```bash
poetry init
poetry install
```
and it should take care of everything. 

If you are adamant you want to install from a requirements.txt, you can also use poetry (or other tools like dephell, I think) to generate one from the `pyproject.toml` file:
```bash
poetry export -f requirements.txt --output requirements.txt
```

**Comment by Asifbinsyed** [comment]
Thanks a lot for your detailed explanation.
